### ISSUE TITLE
怎麽修改main.py

### ISSUE THREAD

**Issue by laker0824** [Aixzk/ESurfingPy-CLI#1]
![image](https://user-images.githubusercontent.com/71869839/134761127-e29a45d9-40db-443a-ab35-459eef3bf0c3.png)

**Comment by Aixzk** [comment]
`main.py` 中主要是使用了 `click` 模块提供命令行功能，负责处理命令行中的参数并传递给 `ESurfingPy.py` 中的函数。
上图中 return 的上一行便是调用 `ESurfingPy.py` 的 `login` 函数，其他大部分都只是实现命令行功能的代码。
你可以在你的 python 文件中 `import ESurfingPy`，并传参调用其中的 `login`, `logout` 函数。

**以下是各个文件的主要功能：**
- `main.py` - 提供命令行功能；
- `ESurfingPy.py` - 实现登录和登出校园；
- `theocr.py` - 识别验证码；
- `RSA.py` - 拼接并 RSA 加密文本；
- `Auto.py` - 自动模式；

**Comment by laker0824** [comment]
主要是我不知道要改main.py的哪些参数

**Comment by Aixzk** [comment]
如果你只是想运行这个程序，我不推荐你通过修改  `main.py` 来运行。

你可以参考项目下面说明中的 `应用` 的 `Win10 快速一键登录/登出` ；
如果在 “目标” 后面只加个 `login` ，运行快捷方式时程序会依次要求填写缺少的参数。

当然你也可以用 cmd 等调用该程序时后面附加命令行参数，关于命令行的更多知识，你可以网上搜索。

**Comment by laker0824** [comment]
请问这个程序用什么框架编译比较好

**Comment by Aixzk** [comment]
不太清楚你问的问题，如果你问的是用什么来编译的话，我是在 Windows10 的 conda 虚拟环境下用 pyinstaller 编译的。

**Comment by Aixzk** [comment]
由于长时间没有回复，现先关闭该 issue，如果还有问题可以重新打开。
